// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GutarWorkshopDB.Models;

public partial class GuitarBuild
{
    public int BuildId { get; set; }

    public int BodyShapeId { get; set; }

    public int TopDeckMaterialId { get; set; }

    public int BottomDeckMaterialId { get; set; }

    public int NeckMaterialId { get; set; }

    public int NeckShapeId { get; set; }

    public int NeckScaleId { get; set; }

    public int FretNubmberTypeId { get; set; }

    public int FingerboardMaterialId { get; set; }

    public int HeadstockStyleId { get; set; }

    public int TuningMachineId { get; set; }

    public int ColorId { get; set; }

    public int FinishId { get; set; }

    public int UserId { get; set; }

    public int StringId { get; set; }

    public decimal TotalPrice { get; set; }

    public virtual BodyShape BodyShape { get; set; }

    public virtual WoodsType BottomDeckMaterial { get; set; }

    public virtual GuitarColor Color { get; set; }

    public virtual WoodsType FingerboardMaterial { get; set; }

    public virtual Finish Finish { get; set; }

    public virtual FretNumberType FretNubmberType { get; set; }

    public virtual HeadstockStyle HeadstockStyle { get; set; }

    public virtual WoodsType NeckMaterial { get; set; }

    public virtual NeckScale NeckScale { get; set; }

    public virtual NeckShape NeckShape { get; set; }

    public virtual StringType String { get; set; }

    public virtual WoodsType TopDeckMaterial { get; set; }

    public virtual TuningMachine TuningMachine { get; set; }

    public virtual User User { get; set; }
}