// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GutarWorkshopDB.Models;

public partial class GuitarOrder
{
    public int OrderId { get; set; }

    public int UserId { get; set; }

    public int BuildId { get; set; }

    public DateTime OrderDateTime { get; set; }

    public decimal Price { get; set; }

    public string OrderStatus { get; set; }

    public string PhoneNumber { get; set; }

    public string DeliveryAddress { get; set; }

    public string Email { get; set; }

    public virtual GuitarBuild Build { get; set; }

    public virtual User User { get; set; }
}