// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GutarWorkshopDB.Models;

public partial class TuningMachine
{
    public int MachineId { get; set; }

    public string MachineName { get; set; }

    public decimal Price { get; set; }

    public virtual ICollection<GuitarBuild> GuitarBuilds { get; set; } = new List<GuitarBuild>();
}