// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GutarWorkshopDB.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Login { get; set; }

    public string PasswordHash { get; set; }

    public int? RoleId { get; set; }

    public virtual ICollection<GuitarBuild> GuitarBuilds { get; set; } = new List<GuitarBuild>();

    public virtual ICollection<GuitarOrder> GuitarOrders { get; set; } = new List<GuitarOrder>();

    public virtual ICollection<RepairOrder> RepairOrders { get; set; } = new List<RepairOrder>();

    public virtual Role Role { get; set; }
}