// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GutarWorkshopDB.Models;

public partial class WoodsType
{
    public int TypeId { get; set; }

    public string WoodName { get; set; }

    public string PartType { get; set; }

    public decimal Price { get; set; }

    public virtual ICollection<GuitarBuild> GuitarBuildBottomDeckMaterials { get; set; } = new List<GuitarBuild>();

    public virtual ICollection<GuitarBuild> GuitarBuildFingerboardMaterials { get; set; } = new List<GuitarBuild>();

    public virtual ICollection<GuitarBuild> GuitarBuildNeckMaterials { get; set; } = new List<GuitarBuild>();

    public virtual ICollection<GuitarBuild> GuitarBuildTopDeckMaterials { get; set; } = new List<GuitarBuild>();
}